[env]
PUBLIC_PATH = "public"

[tasks.test]
command = "cargo"
args = ["test", "--", "--test-threads", "1"]

[tasks.check]
command = "cargo"
args = ["clippy"]

[tasks.ready]
command = "gem"
args = ["install", "asciidoctor", "rouge"]

[tasks.site]
script = [
    "mkdir -p ${PUBLIC_PATH}",
    "asciidoctor README.adoc -o ${PUBLIC_PATH}/index.html"
]

[tasks.appimage]
script = [
    "cargo install --path . --locked --root AppDir/usr",
    "stat AppDir/AppRun || ln -s usr/bin/herm AppDir/AppRun",
    "stat appimagetool-x86_64.AppImage || wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage",
    "chmod +x appimagetool-x86_64.AppImage",
    "./appimagetool-x86_64.AppImage AppDir"
]